### ISSUE TITLE
mono upgrade

### ISSUE THREAD

**Issue by jabbera** [jacobalberty/mb-base-docker#1]
Mono 3.10 is the recommended version by the MB dev. (3.12 has some outstanding bugs according to mb dev). 3.2.8 does not support SSL.

**Comment by jacobalberty** [comment]
Good call working on getting it updated to mono 3.10 looks like the image will have to be downgraded to wheezy to work with the newer mono due to some dependency issues but i'll hopefully have it updated shortly.

**Comment by jabbera** [comment]
I gave it the good old college try by just chaining the base to mono:3.10, but then I hit the following when installing MB. Hopefully your docker skills are better then mine. I'm just getting started and it feels like learning git all over again.

[91mE: Package 'libwebp5' has no installation candidate
[0m

**Comment by jacobalberty** [comment]
New build is running now, tested all the way to playback on my  tv unfortunately i had to move from debian to ubuntu (So the image grew a bit (approximately 52mb bigger) but everything still behaves the same and it runs without using a launcher so docker can set user still if you're bind mounting a password and group file.
